[INV-90] Implement Review Card Component
vention-js-lab/invention-stayhub-frontend pull request #10
Opened 2024-11-27 19:58 UTC by muhammadjon8

## Review Card Component
![image](https://github.com/user-attachments/assets/0f3c54f9-bbfb-49ec-b705-5651443d28d5)

## When clicked 'show more' button
![image](https://github.com/user-attachments/assets/119e8e26-8680-4792-91db-acf242ca9e33)

2024-11-27 20:28 UTC, farrooh requested changes

2024-11-27 20:28 UTC, farrooh commented on src/modules/home/components/review-card.tsx
Move types, interfaces (other than Props), and styles to separate files.

2024-11-27 20:28 UTC, farrooh commented on src/modules/home/components/review-card.tsx
Use optional chaining and alternative values to avoid type errors. For example: `review?.user?.photo || review?.user?.firstName?.[0] || " ";`

2024-11-27 20:28 UTC, farrooh commented on src/modules/home/components/review-card.tsx
> +                {review.user.firstName ? review.user.firstName : ''} {review.user.lastName ? review.user.lastName : ''}
Simplify these with OR operator. `review?.user?.firstName || ""`

2024-11-27 20:28 UTC, farrooh commented on src/modules/home/components/review-card.tsx
> +            {review.content ? review.content.slice(0, 150) : ''}...
Correction: `{review.content ? '${review.content.slice(0, 150)}...' : ''}`
Right now, if review.content is not available, the result will look like: `...`, which is not correct. 
Create a function that does this and use it. Or you can do it with styles as well, which is better in my opinion.

2024-11-27 20:28 UTC, farrooh commented on src/modules/home/routes/home.route.tsx
Remove ReviewCard from this page. I think it was only for development preview purposes.

2024-11-28 05:50 UTC, NegatiV-64 approved these changes

2024-11-28 07:21 UTC, farrooh requested changes

2024-11-28 07:21 UTC, farrooh commented on src/modules/home/components/review-card.tsx
> +const styles = {
Separate file for this as well

2024-11-28 08:11 UTC, farrooh approved these changes

2024-11-28 08:12 UTC, merged