INV-52/Add-booking-logic
vention-js-lab/invention-stayhub-frontend pull request #12
Opened 2024-11-29 18:14 UTC by blackseriesC63

Before booking
<img width="608" alt="Screenshot 2024-11-29 at 15 42 08" src="https://github.com/user-attachments/assets/cb5f9960-2de8-4bca-aa77-85b9ef339583">

After Booking
<img width="469" alt="Screenshot 2024-11-29 at 15 42 19" src="https://github.com/user-attachments/assets/c5e1b019-36cf-4619-9a4e-e63feffea325">

https://github.com/user-attachments/assets/149797be-7961-41b0-ad73-44a6f7168985

2024-11-29 19:21 UTC, ShahobiddinIsmoilov requested changes

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/api/booking.api.ts
> +export async function createBooking(payload: CreateBookingPayload): Promise<void> {
Please use tanstack query mutations

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +const ReservationCard: React.FC<ReservationCardProps> = ({
Please use function keyword instead of array functions

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +      console.error('Error creating booking:', error);
Please don't log to console

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +      alert('Reservation confirmed!');
Please use showSnackbar type success instead of alert

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +      alert('Failed to create booking. Please try again.');
Please use showSnackbar type error instead of alert

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/types/accommodation.type.ts
> +export interface Booking {
Please move it to its own file

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +    backgroundColor: isButtonEnabled ? '#FF385C' : '#ddd',
Please use ```theme.palette.secondary.main``` and ```theme.palette.action.disabled```

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +    color: isButtonEnabled ? '#fff' : '#aaa',
Here as well, please try to get appropriate color from ```theme```

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +      await createBooking(bookingPayload);
Please use tanstack query mutations and handle success and errors with it

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +      alert('Please select valid dates.');
Please use showSnackbar

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +      alert('The selected dates are unavailable. Please choose different dates.');
Please use showSnackbar

2024-11-29 19:21 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/components/reservation-card.tsx
> +  const isDateUnavailable = (date: Dayjs): boolean => {
Please move this to reservation card util. Also, please move ```shared/utils/reservatoin-card.util.ts``` to ```modules/accommodations/reservation-card.util.ts``` (and please correct the typo)

2024-12-02 12:37 UTC, farrooh commented
I believe I can approve this once @ShahobiddinIsmoilov 's  requests are satisfied.

2024-12-05 04:47 UTC, closed without merging