[INV-101] Deploy frontend
vention-js-lab/invention-stayhub-frontend pull request #18
Opened 2024-12-04 08:47 UTC by muhammadjon8

# Pull request for: [TICKET_NUMBER]

## Description

_Please replace this text with a description of the changes in this PR or attach a screenshots/video of the changes._

## Checklist

- [x] I have manually tested the changes and related features
- [x] I have run the linter and fixed any possible issues
- [x] I have run the tests and fixed any possible issues
- [x] I have run the build and fixed any possible issues

2024-12-04 10:27 UTC, NegatiV-64 requested changes

2024-12-04 10:27 UTC, NegatiV-64 commented on Dockerfile
> +RUN npm install
Use ci instead

2024-12-04 10:27 UTC, NegatiV-64 commented on Dockerfile
> +# Step 6: Build the application for production
Set NODE ENV as production

2024-12-04 10:27 UTC, NegatiV-64 commented on Dockerfile
> +CMD ["nginx", "-g", "daemon off;"]
No need to run Nginx servier

2024-12-04 10:27 UTC, NegatiV-64 commented on nginx.conf
```nginx
user nginx;
worker_processes 5;
worker_rlimit_nofile 8192;

error_log  /dev/stderr warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # Basic Settings
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    types_hash_max_size 2048;
    server_tokens off;
    ignore_invalid_headers on;

    # Log Formats
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
	  map $status $loggable {
		  ~^[23]  0;
		  default 1;
	  }
    access_log  /dev/stdout  main if=$loggable;

    # MIME Settings
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Limits
    limit_req_zone $binary_remote_addr zone=dos_attack:20m rate=30r/m;

    # Gzip Settings
    gzip on;
    gzip_disable "msie6";
    gzip_vary off;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 1000;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # React Router will handle everything
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Only handle 50x errors with Nginx
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
    }
}
```

2024-12-06 17:59 UTC, muhammadjon8 commented
![image](https://github.com/user-attachments/assets/06327d63-2264-4d04-a031-e75bda75ef77)
I think i completed this part as well

2024-12-07 06:03 UTC, NegatiV-64 approved these changes

2024-12-07 06:04 UTC, merged