[INV-37] Add login page & logic
vention-js-lab/invention-stayhub-frontend pull request #2
Opened 2024-11-13 13:34 UTC by ShahobiddinIsmoilov

https://github.com/user-attachments/assets/90b6b0b7-8738-4dd4-a0c1-78f1ae770677

2024-11-13 15:29 UTC, NegatiV-64 requested changes

2024-11-13 15:29 UTC, NegatiV-64 commented on src/hooks/auth.hook.tsx
> +    const baseURL = import.meta.env.VITE_API_BASE_URL;
I'd suggest to create an api client using axios instance

2024-11-13 15:29 UTC, NegatiV-64 commented on src/hooks/auth.hook.tsx
> +      const response = await fetch(`${baseURL}/auth/login`, {
Please use Tanstack Query

2024-11-13 15:29 UTC, NegatiV-64 commented on src/hooks/auth.hook.tsx
> +        err instanceof Error ? err.message : 'An unexpected error occurred while trying to log in. Please try again';
Please write an util function to parse the errors

2024-11-13 15:29 UTC, NegatiV-64 commented on src/hooks/auth.hook.tsx
> +  const error = useSelector((state: StoreState) => state.auth.error);
Add logic for page refreshes

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/components/register-link.tsx
> +import { styles } from '../styles/styles';
Please move the styles related to this component, to this component

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/forms/login-form.tsx
> +import { styles } from '../styles/styles';
Please move the styles related to this component, to this component

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/forms/login-form.tsx
> +    if (status === 'success') {
Remove the useEffect

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/forms/login-form.tsx
> +    await login({ email: loginFormData.email, password: loginFormData.password });
Handle the redirect logic in this place

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/forms/login-form.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-misused-promises
Disable this rule in eslint config file

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/forms/login-form.tsx
> +          {status === 'pending' ? 'Logging in...' : 'Log in'}
Create a special LoadingButton component or use from MUI

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/routes/login.route.tsx
> +import { styles } from '../styles/styles';
Please move the styles related to this component, to this component

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/types/auth-status.type.ts
Move this file to the shared level

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/types/auth.type.ts
Move this file to the shared level

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/types/current-user.type.ts
Move it the auth type file

2024-11-13 15:29 UTC, NegatiV-64 commented on src/modules/auth/login/utils/get-local-user.util.ts
> +  return JSON.parse(localUser) as CurrentUser;
Validate the JSON parsed data

2024-11-13 15:29 UTC, NegatiV-64 commented on src/styles/root.css
> +@import url('https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap');
MUI uses Roboto, let's keep use Roboto

2024-11-13 15:29 UTC, NegatiV-64 commented on src/styles/root.css
> +@import url('https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap');
See: https://mui.com/material-ui/getting-started/installation/#roboto-font

2024-11-14 13:37 UTC, NegatiV-64 requested changes

2024-11-14 13:37 UTC, NegatiV-64 commented on src/modules/auth/types/login-form-data.type.ts
> +export interface LoginFormData {
Infer types from the schema of zod

2024-11-14 13:37 UTC, NegatiV-64 commented on src/shared/hooks/auth.hook.tsx
> +      dispatch(setStatus('idle'));
if there's no user => anyway solve the status

2024-11-14 13:37 UTC, NegatiV-64 commented on src/shared/hooks/auth.hook.tsx
> +    loginMutation.mutate(credentials, {
Please move the API call to the login form submit:

- onSubmit in the form calls the login API => returns tokens
- onSubmit also handles errors during the API call
- Login function here accepts the tokens and just writes them into the localstorage and store. 

As a result, register page can reuse the same function

2024-11-14 13:37 UTC, NegatiV-64 commented on src/styles/root.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
[Use npm package](https://www.npmjs.com/package/@fontsource/roboto)

2024-11-14 15:24 UTC, muhammadjon8 submitted a review, later dismissed

2024-11-14 19:23 UTC, NegatiV-64 approved these changes

2024-11-14 19:26 UTC, merged